set nocompatible
set autoindent
set tabstop=2
set shiftwidth=2
set expandtab
set softtabstop=2
set number
set ruler
set hlsearch
syntax on
colorscheme desert
autocmd FileType python setlocal tabstop=4 shiftwidth=4 softtabstop=4
